import asyncio
from sqlalchemy import text
from app.db.session import engine

async def setup_db():
    async with engine.connect() as conn:
        print("Creating missing tables...")
        
        # 1. Create clients table
        await conn.execute(text("""
            CREATE TABLE IF NOT EXISTS public.clients (
                client_uuid uuid NOT NULL DEFAULT gen_random_uuid (),
                client_id text NULL,
                client_name text NULL,
                client_email text NULL,
                client_phone text NULL,
                client_gender text NULL,
                client_country text NULL,
                client_job_domain text NULL,
                client_experience text NULL,
                client_skills text NULL,
                client_resume text NULL,
                client_cover_letter text NULL,
                client_portfolio text NULL,
                client_github text NULL,
                client_linkedin text NULL,
                created_at timestamp with time zone NULL DEFAULT now(),
                client_chosen_alternative_jobroles text[] NULL DEFAULT '{}'::text[],
                client_expereince_rounded numeric NULL,
                password_hash text NULL,
                is_active boolean NULL DEFAULT false,
                is_paid boolean NULL DEFAULT false,
                updated_at timestamp with time zone NULL,
                domain_changed_at timestamp with time zone NULL,
                CONSTRAINT clients_pkey PRIMARY KEY (client_uuid),
                CONSTRAINT clients_client_email_key UNIQUE (client_email)
            );
        """))
        print("✅ Clients table created.")

        # 2. Create saved_jobs table
        await conn.execute(text("""
            CREATE TABLE IF NOT EXISTS public.saved_jobs (
                id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                client_id text NOT NULL,
                saved_at timestamp with time zone NULL DEFAULT now(),
                job_id text NULL,
                job_url text NULL,
                title text NULL,
                company text NULL,
                company_image_url text NULL,
                location_city text NULL,
                location_state text NULL,
                location_country text NULL,
                location_display text NULL,
                is_remote text NULL,
                work_location text NULL,
                job_type_label text NULL,
                w2_c2c_type text NULL,
                employment_type text NULL,
                badge_job_type text NULL,
                date_posted text NULL,
                salary text NULL,
                salary_min text NULL,
                salary_max text NULL,
                salary_interval text NULL,
                experience text NULL,
                skills text NULL,
                job_url_external text NULL,
                description text NULL,
                tech_stack text NULL,
                scraped_at text NULL,
                CONSTRAINT saved_jobs_pkey PRIMARY KEY (id)
            );
        """))
        print("✅ Saved_jobs table created.")

        # 3. Create applied_jobs table
        await conn.execute(text("""
            CREATE TABLE IF NOT EXISTS public.applied_jobs (
                id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                client_id text NOT NULL,
                applied_at timestamp with time zone NULL DEFAULT now(),
                job_id text NULL,
                job_url text NULL,
                title text NULL,
                company text NULL,
                company_image_url text NULL,
                location_city text NULL,
                location_state text NULL,
                location_country text NULL,
                location_display text NULL,
                is_remote text NULL,
                work_location text NULL,
                job_type_label text NULL,
                w2_c2c_type text NULL,
                employment_type text NULL,
                badge_job_type text NULL,
                date_posted text NULL,
                salary text NULL,
                salary_min text NULL,
                salary_max text NULL,
                salary_interval text NULL,
                experience text NULL,
                skills text NULL,
                job_url_external text NULL,
                description text NULL,
                tech_stack text NULL,
                scraped_at text NULL,
                CONSTRAINT applied_jobs_pkey PRIMARY KEY (id)
            );
        """))
        print("✅ Applied_jobs table created.")

        # 4. Add test client C-106 if not exists
        await conn.execute(text("""
            INSERT INTO public.clients (client_id, client_name, client_email, is_active)
            VALUES ('C-106', 'Test User', 'test@example.com', true)
            ON CONFLICT (client_email) DO NOTHING;
        """))
        print("✅ Test client C-106 added.")
        
        await conn.commit()

if __name__ == "__main__":
    asyncio.run(setup_db())
